Metadata workflow
pcm32/atlas-baseline-meta-analysis pull request #1
Opened 2021-06-14 15:29 UTC by pcm32

This PR reorganises the setup to have a data and a metadata workflow, and adds the metadata workflow.

2022-10-20 08:41 UTC, irisdianauy commented on data-analysis/Snakefile
> +	irap_gtf2featlength --gtf {input.gtf} --out {params.lengths} --cores {threads}
Has running this part finally worked?  Have you also tried using the singularity container for irap?

2022-10-20 08:41 UTC, irisdianauy commented on data-analysis/Snakefile
> +	irap_gtf2featlength --gtf {input.gtf} --out {params.lengths} --cores {threads}
This is how ISL calls the iRAP container, and relevant variables are set in the ISL env.

2022-10-24 09:00 UTC, pmb59 requested changes
It looks very good @anilthanki 

In addition to the comments I have left, memory allocation based on retrials could be implemented in case merging /analysing dozens/hundreds of datasets requires high RAM mem.

Future work you could address, perhaps in other PRs:
1 - adding CI (via github actions) that run snakemake with test data. E.g. merging two accessions
2- monitor mage-tab-merger version > 0.0.4. If IDF merging is provided, it would be good to have have it too, as the formal definition MAGE-TAB requires IDF (Investigation Description Format) and SDRF (Sample and Data Relationship Format).

2022-10-24 09:00 UTC, pmb59 commented on README.md
> +export ACCESSIONS="E-MTAB-4395,E-MTAB-4342,E-MTAB-4128"
I assume all accessions need to come from same the species. Could you implement a check in the Snakefile that confirms this? 

A related question. Do all accessions here are 'baseline' RNA-seq in Atlas, right? Could this also be checked so that microarrays or proteomics experiments are not included by mistake? This info is available in the XML, an option could be using something like [this](https://github.com/ebi-gene-expression-group/experiment_metadata/blob/develop/zooma-mappings-wf/rules/common.smk#L42)

2022-10-24 09:00 UTC, pmb59 commented on README.md
> +E-SUPR-1.gtf                                    E-SUPR-1-analysis-methods.tsv
what is stored in the GTF file?  is it generated by the workflow? If it is just copied from refgenie and not altered in any way, I am wondering if we should keep the original filename.

2022-10-24 09:00 UTC, pmb59 commented on README.md
> +To merge the metadata of datasets, we use within a Snakemake workflow the [MAGE-Tab-merger](https://pypi.org/project/MAGE-Tab-merger/) package to produce:
Is it possible to merge IDFs? the MAGE-Tab Merger package currently says 

> Note: IDF merging is still work in progress.

Do we need merge a merged IDF?

2022-10-24 09:00 UTC, pmb59 commented on README.md
```suggestion
The repository contains workflows for metadata generation and data analysis.
```

2022-10-24 09:00 UTC, pmb59 commented on README.md
> +export COVARIATE='organism part'
a bit of explanation below about this parameter could help. What are the consequences of using different COVARIATEs?

2022-10-24 09:00 UTC, pmb59 commented on data-analysis/bin/get_assay_groups.pl
> +#!/usr/bin/env perl
Maybe you can add [atlas-bash-util](https://github.com/ebi-gene-expression-group/atlas-bash-util) as a submodule and use `get_assay_groups.pl` from there?
(if you do, please double-check that the code is actually the same )

Same comment for some other scripts that are here https://github.com/ebi-gene-expression-group/atlas-analysis  (if appropriate)

2022-10-24 09:00 UTC, pmb59 commented on data-analysis/bin/quantile_normalize.sh
Could you rename this script `quantile_normalize_meta.sh` (or similar) so we don't confuse it with the one here? https://github.com/ebi-gene-expression-group/atlas-analysis/tree/develop/norm

2022-10-24 09:00 UTC, pmb59 commented on data-analysis/bin/quantile_normalize.sh
> +#trap 'rm -f ${tmp_files}.*' INT TERM EXIT
why this is not necessary anymore?

2022-10-24 09:00 UTC, pmb59 commented on meta-data/Snakefile
> +def existing_or_retrieve(type):
this could be moved above with other helper functions

2022-10-24 09:00 UTC, pmb59 commented on meta-data/Snakefile
> +            return rules.retrieve_data.output.data
I think you should do here:
```
 if type == "path":
else if type == "data":
else
```
to handle explicitly the type "data"

2022-10-24 09:00 UTC, pmb59 commented on data-analysis/Snakefile
> +rule lengths:
could you rename this rule so the name is more informative?

2022-10-24 09:00 UTC, pmb59 commented on data-analysis/Snakefile
> +METRICS=['tpm', 'fpkm']
Not all accessions have `tpm` or `fpkm` metrics. In some (rare cases) it is only one of them. Optionally, you could implement a check for that

2022-10-24 09:00 UTC, pmb59 commented on meta-data/Snakefile
> +        echo "Output accession\t" {params.new_accession} >> {output}
In bulk analysis, the file -analysis-methods.tsv has the actual analysis methods for each accession.
Here we don't have that. I wonder if this file should be named -analysis-methods.tsv or something different.

Maybe you could add also here species, and covariate information used for the meta-analysis

2022-10-24 09:00 UTC, pmb59 commented on data-analysis/Snakefile
> +rule irap_raw2metric:
```suggestion
rule irap_raw2metric:
    """
    Generates TPM and FPKM metrics from counts for accessions 
    """
```

2022-10-24 09:00 UTC, pmb59 commented on data-analysis/bin/batch_correction_v2.R
>  batch_corrected<-correct_batch_effect(experiment = experimentSummary, model= ~organism_part, method='ComBat')
why "Combat" is used and not others?

2022-10-24 09:00 UTC, pmb59 commented on data-analysis/Snakefile
> +rule transform2R:
I would recommend to add log files to the rules in this Snakefile

2022-10-24 10:25 UTC, pmb59 commented on data-analysis/Snakefile
> +
I usually include this in my workflows:
```suggestion
# set minimum snakemake version
min_version("6.6.1")

```

2022-10-25 08:31 UTC, anilthanki commented on data-analysis/Snakefile
> +	irap_gtf2featlength --gtf {input.gtf} --out {params.lengths} --cores {threads}
Yes I managed to get it working..

2022-10-25 08:33 UTC, anilthanki commented on README.md
> +export ACCESSIONS="E-MTAB-4395,E-MTAB-4342,E-MTAB-4128"
Thanks.. yes all accession needs to be from same species, 

I will add checks for species and experiment type

2022-10-25 08:34 UTC, anilthanki commented on README.md
> +E-SUPR-1.gtf                                    E-SUPR-1-analysis-methods.tsv
It's copied from RefGenie, we can use original file name its just that then it needs to supplied to second workflow as a parameter..

2022-10-25 08:41 UTC, anilthanki commented on meta-data/Snakefile
> +        echo "Output accession\t" {params.new_accession} >> {output}
In discussion with Pablo, he mentioned that we should generate our own analysis-methods file for this describing the process we followed, 

I am planning to add bit description of steps the process follows, I will try to replicated bulk analysis analysis-methods.tsv

2022-10-25 15:04 UTC, anilthanki commented on README.md
> +export ACCESSIONS="E-MTAB-4395,E-MTAB-4342,E-MTAB-4128"
Added fix in [d66c44e](https://github.com/ebi-gene-expression-group/atlas-baseline-meta-analysis/pull/1/commits/d66c44e590f3bcc7f68fe71ff0767cb144aa0e9c)

2022-10-25 15:08 UTC, anilthanki commented on data-analysis/bin/quantile_normalize.sh
> +#trap 'rm -f ${tmp_files}.*' INT TERM EXIT
Pipeline was failing with this command in place.

2022-10-25 15:11 UTC, anilthanki commented on meta-data/Snakefile
> +def existing_or_retrieve(type):
Fixes in [71f1946](https://github.com/ebi-gene-expression-group/atlas-baseline-meta-analysis/pull/1/commits/71f1946fdec7dfd021a41070a2a92af520a4ba58)

2022-10-25 15:19 UTC, anilthanki commented on data-analysis/Snakefile
> +rule lengths:
Fixes in [6104229](https://github.com/ebi-gene-expression-group/atlas-baseline-meta-analysis/pull/1/commits/6104229d0e09f756e0bdb3e999f52a1ec4a49c27)

2022-10-26 13:25 UTC, anilthanki commented on data-analysis/bin/quantile_normalize.sh
fixes in [d5a1a00](https://github.com/ebi-gene-expression-group/atlas-baseline-meta-analysis/pull/1/commits/d5a1a00fb461a24d974bd526ed88518a004eab7b)

2022-10-26 13:35 UTC, anilthanki commented on meta-data/Snakefile
> +            return rules.retrieve_data.output.data
Fixes in [555bd20](https://github.com/ebi-gene-expression-group/atlas-baseline-meta-analysis/pull/1/commits/555bd201cac7167c6113b2859f1620589aa0adb8)

2022-10-31 17:47 UTC, anilthanki commented on data-analysis/Snakefile
> +rule transform2R:
adds logs in data-analysis workflow in commit [5efeb2a](https://github.com/ebi-gene-expression-group/atlas-baseline-meta-analysis/pull/1/commits/5efeb2af09fb7f12d2ca8086a48b6b840e18f0e1)

2022-10-31 17:47 UTC, anilthanki commented on data-analysis/Snakefile
> +rule lengths:
adds renamed file in [7925cdb](https://github.com/ebi-gene-expression-group/atlas-baseline-meta-analysis/pull/1/commits/7925cdb7a688d2b6d6df6be16ea3e141062aac1e)

2022-11-07 16:05 UTC, anilthanki commented on data-analysis/bin/get_assay_groups.pl
> +#!/usr/bin/env perl
Looks like it was added in older version of pipeline but not used.. removed along with some other un-used scripts in [03cb628](https://github.com/ebi-gene-expression-group/atlas-baseline-meta-analysis/pull/1/commits/03cb628ebcec7186e6ad865442fd54f883d301cd)

2022-11-07 16:40 UTC, anilthanki commented on meta-data/Snakefile
> +        echo "Output accession\t" {params.new_accession} >> {output}
added some more info in [3b5f7f8](https://github.com/ebi-gene-expression-group/atlas-baseline-meta-analysis/pull/1/commits/3b5f7f82bbdc760f88e098a3ab72e00892076294)

2022-11-07 17:02 UTC, anilthanki commented on data-analysis/Snakefile
> +METRICS=['tpm', 'fpkm']
here `irap_raw2metric ` rule generates `tpm` and `fpkm` matrices from counts for the accessions

2022-11-08 13:26 UTC, anilthanki commented on README.md
> +To merge the metadata of datasets, we use within a Snakemake workflow the [MAGE-Tab-merger](https://pypi.org/project/MAGE-Tab-merger/) package to produce:
I dont see much progress on IDF merging after that comment...

2022-11-08 13:42 UTC, anilthanki commented on data-analysis/bin/batch_correction_v2.R
>  batch_corrected<-correct_batch_effect(experiment = experimentSummary, model= ~organism_part, method='ComBat')
`Combat` was chosen as a bath_correction method by predecessors but looking at [this paper](https://www.biorxiv.org/content/10.1101/2020.05.22.111161v2.full), looks like it was a good choice. 

`MNN` and `RUV` are provided as alternatives

2022-11-30 10:12 UTC, anilthanki commented on README.md
> +export COVARIATE='organism part'
Covariates are the factors which may affect the final results regardless of process followed. 

Here we are using `organism part`, one another example of covariate could be biological condition

2022-11-30 10:31 UTC, anilthanki commented on data-analysis/bin/quantile_normalize.sh
> +#trap 'rm -f ${tmp_files}.*' INT TERM EXIT
Added trap command back in [66803b3](https://github.com/ebi-gene-expression-group/atlas-baseline-meta-analysis/pull/1/commits/66803b30f9b2d9726c7c1f373319fdee7dc0ba63)

2023-01-20 13:13 UTC, pmb59 reviewed
LGTM, almost production-ready!

I've left few comments

2023-01-20 13:13 UTC, pmb59 commented on data-analysis/Snakefile
> +min_version("6.6.1")
I would move this chunk to the top of the script

2023-01-20 13:13 UTC, pmb59 commented on README.md
> +Most files are self explanatory, the `selected_studies.txt` files contains a comma separate list of the original accessions used.
```suggestion
Most files are self explanatory, the `selected_studies.txt` files contains a comma separate list of the original accessions used. The `gtf` is copied from Refgenie references.
```

2023-01-20 13:13 UTC, pmb59 commented on README.md
> +Jenkins job for this part of workflow is at http://gene-expression.ebi.ac.uk/jenkins/job/bulk_baseline_meta_analysis_dataprep/
Although unauthorised users won't have access to this link, we usually don't give jenkins information across public Atlas repos.  I would suggest to write an internal SOP for baseline meta-analysis where this info can be specified and detailed.

The SOP could also indicate the role of curators in this processes.

2023-01-20 13:13 UTC, pmb59 commented on curation/README.md
> +# Selection of studies that can be merged in mete-analysis
```suggestion
# Selection of studies that can be merged in meta-analysis
```

2023-01-20 13:13 UTC, pmb59 commented on curation/README.md
> +# Selection of studies that can be merged in mete-analysis
what's the purpose of this file? does it need editing by curators?

2023-01-20 13:13 UTC, pmb59 commented on meta-data/Snakefile
> +    return optionals
is it fine for downstream processes to return `optionals=""`?

2023-01-20 13:13 UTC, pmb59 commented on meta-data/Snakefile
> +    if "retrieve_data" in config or ('target' in config and config['target'] == TARGET_ANALYSIS_POST_CURATION):
what if both options are in `config`?

2023-01-20 13:13 UTC, pmb59 commented on meta-data/Snakefile
> +	echo "Retrieved GTF using RefGenie for the species\t" {params.species} >> {output}
Maybe you could add here the: 
- MAGETab-merger version
- Refgenie version

2023-01-20 13:13 UTC, pmb59 commented on data-analysis/bin/transform2R.r
> +
this R script needs abundant style editing

2023-01-20 13:13 UTC, pmb59 commented on data-analysis/Snakefile
> +rule batch_correction_v2:
why is  named`_v2`?

2023-01-20 13:13 UTC, pmb59 commented on .gitmodules
> +[submodule "data-analysis/bin/atlas-bash-util"]
where is this submodule actually used in the repo?

2023-01-20 13:13 UTC, pmb59 commented on README.md
> +Jenkins job for this part of workflow is at http://gene-expression.ebi.ac.uk/jenkins/job/bulk_baseline_meta_analysis/
Same as before, better move this to SOP

2023-01-30 13:54 UTC, anilthanki commented on README.md
> +Jenkins job for this part of workflow is at http://gene-expression.ebi.ac.uk/jenkins/job/bulk_baseline_meta_analysis_dataprep/
Jenkins link removed

2023-01-30 13:54 UTC, anilthanki commented on README.md
> +Jenkins job for this part of workflow is at http://gene-expression.ebi.ac.uk/jenkins/job/bulk_baseline_meta_analysis/
Jenkins link removed

2023-01-30 13:58 UTC, anilthanki commented on meta-data/Snakefile
> +    if "retrieve_data" in config or ('target' in config and config['target'] == TARGET_ANALYSIS_POST_CURATION):
It should consider `retrieve_data` and continue

2023-01-30 14:00 UTC, anilthanki commented on meta-data/Snakefile
> +    return optionals
Its returning empty string so I don't see any issue

2023-01-30 14:03 UTC, anilthanki commented on meta-data/Snakefile
> +	echo "Retrieved GTF using RefGenie for the species\t" {params.species} >> {output}
Versions not specified in conda env to be able to use latest available. We can either specify and use hardcoded version or leave it as it is..

As both are separate conda env cant use both in one rule and will need to detect and store version in global var

2023-01-30 14:07 UTC, anilthanki commented on data-analysis/Snakefile
> +rule batch_correction_v2:
It came from predecessors, its good idea to change it

2023-01-30 14:10 UTC, anilthanki commented on data-analysis/Snakefile
> +rule batch_correction_v2:
fixed in 477e0c5 and [6bf98cb](https://github.com/ebi-gene-expression-group/atlas-baseline-meta-analysis/pull/1/commits/6bf98cbabeb95b290ae2fed7f1b2443f0491e6c4)

2023-01-30 14:18 UTC, anilthanki commented on data-analysis/Snakefile
> +min_version("6.6.1")
Fixed in [23ae1c3](https://github.com/ebi-gene-expression-group/atlas-baseline-meta-analysis/pull/1/commits/23ae1c39f188c4bf284bf23741e49a11b36469ea)

2023-01-30 15:35 UTC, anilthanki commented on data-analysis/bin/transform2R.r
> +
Fixed in [00e7c4d](https://github.com/ebi-gene-expression-group/atlas-baseline-meta-analysis/pull/1/commits/00e7c4d80ec2b42cae2ab76d6f021f0039d7eb78)

2023-01-31 12:25 UTC, anilthanki commented on .gitmodules
> +[submodule "data-analysis/bin/atlas-bash-util"]
It was added to replace some scripts but they were never used so removed submodule as well, removed in [8469691](https://github.com/ebi-gene-expression-group/atlas-baseline-meta-analysis/pull/1/commits/84696915bf3702ffbaa170dfe38432270ee046a3)

2023-02-16 17:57 UTC, pmb59 approved these changes
@anilthanki LGTM!

I've added few other comments.

To avoid overloading this excellent first PR I would recommend that, if your tests are working, merge the PR and list in a new Issue in the repo those potential new features that can be addressed in the future (known covariate bug, improve methods file, standardisation with respect to current bulk pipelines, details on how to select studies, etc.)

2023-02-16 17:57 UTC, pmb59 commented on meta-data/Snakefile
> +            if "rnaseq" in i.getAttribute("experimentType"):
experimentType can be
- 'rnaseq_mrna_baseline'
- 'rnaseq_mrna_differential'

Maybe you want to check here explicitly that the experiments belong to the first case?

2023-02-16 17:57 UTC, pmb59 commented on README.md
> +E-SUPR-1.gtf                                    E-SUPR-1-analysis-methods.tsv
can you add the original GTF filename to the Methods file? (if not done yet)

2023-02-16 17:57 UTC, pmb59 commented on meta-data/Snakefile
> +        echo "Output accession\t" {params.new_accession} >> {output}
You could add here to the versions of IRAP and MAGETab-merger.

2023-02-16 17:57 UTC, pmb59 commented on data-analysis/bin/batch_correction_v2.R
>  batch_corrected<-correct_batch_effect(experiment = experimentSummary, model= ~organism_part, method='ComBat')
you could also add this info to the methods

2023-02-17 09:57 UTC, anilthanki commented
Thanks @pmb59 .. I created https://github.com/ebi-gene-expression-group/atlas-baseline-meta-analysis/issues/2 and https://github.com/ebi-gene-expression-group/atlas-baseline-meta-analysis/issues/3 from comments.. 

Feel free to add more info on them

2023-02-17 10:08 UTC, merged